# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\addtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2
from config import config
from messagebox import messageBox

class Ui_AddTest(object):

    def __init__(self, main):
        self.class_id = main.class_id
        self.class_shortcut = main.class_shortcut
        self.Dialog = QtWidgets.QDialog()
        self.setupUi(self.Dialog)
        self.Dialog.show()
        self.Dialog.exec()

    def saveChanges(self):
        self.test_name = self.lineEdit.text()
        self.test_shortcut = self.lineEdit_2.text()
        conn = None
        try:
            params = config()
            conn = psycopg2.connect(**params)
            cur = conn.cursor()
            cur.execute(f"INSERT INTO sprawdziany (id_przedmiotu, skrot_sprawdzianu, nazwa_sprawdzianu) VALUES ({self.class_id}, '{self.test_shortcut}', '{self.test_name}')")
            conn.commit()
            messageBox('Dodano sprawdzian', QtWidgets.QMessageBox.Information, 'Sukces', 'Pomyślnie dodano sprawdzian.')
        except (Exception, psycopg2.DatabaseError) as e:
            print("Błąd połączenia z bazą danych", e)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(472, 307)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 52, 461, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setMaxLength(50)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 131, 21))
        self.label_2.setObjectName("label_2")

        # Mój kod
        self.pushButton.clicked.connect(self.saveChanges)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dodawanie sprawdzianu"))
        self.label.setText(_translate("Dialog", "Dodawanie sprawdzianu"))
        self.label_7.setText(_translate("Dialog", "Pełna nazwa sprawdzianu"))
        self.label_5.setText(_translate("Dialog", "Skrót sprawdzianu"))
        self.pushButton.setText(_translate("Dialog", "Dodaj sprawdzian"))
        self.label_2.setText(_translate("Dialog", f"Przedmiot: {self.class_shortcut}"))

