# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/updateuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2
import re
import hashlib
from config import config
from messagebox import messageBox


class Ui_UpdateUser(object):

    def __init__(self):
        self.Dialog = QtWidgets.QDialog()
        self.setupUi(self.Dialog)
        self.getAllUsers()
        self.Dialog.show()
        self.Dialog.exec_()

    def getAllUsers(self):
        try:
            params = config()                       # wczytujemy paramtery połaczenia z bazą
            conn = psycopg2.connect(**params)       # łączenie z bazą
            cur = conn.cursor()                     # tworzenie kursora do bazy
            query = f"SELECT email, imie, nazwisko, rola FROM uzytkownicy ORDER BY id_uzytkownika" # query
            cur.execute(query)
            self.userlist = cur.fetchall()

            for row in self.userlist:
                self.comboBox_2.addItem(f"{row[1]} {row[2]}")
        except (Exception, psycopg2.DatabaseError) as err:
            print(f"Błąd połączenia z bazą: {err}")
            return False
        finally:
            if conn is not None:
                conn.close()                        # zamknięcie konektora do bazy
    
    def getUserInfo(self):
        userid = self.comboBox_2.currentIndex()
        roledict = {
            "Uczeń": 1,
            "Nauczyciel": 2,
            "Admin": 3
        }
        try:
            params = config()                       # wczytujemy paramtery połaczenia z bazą
            conn = psycopg2.connect(**params)       # łączenie z bazą
            cur = conn.cursor()                     # tworzenie kursora do bazy
            query = f"SELECT imie, nazwisko, email, haslo, rola FROM uzytkownicy WHERE id_uzytkownika = {userid+1}" # query
            cur.execute(query)
            self.userinfo = cur.fetchall()
            self.lineEdit.setText(self.userinfo[0][0]) # imie
            self.lineEdit_2.setText(self.userinfo[0][1]) # nazwisko
            self.lineEdit_3.setText(self.userinfo[0][2]) # email
            self.lineEdit_4.setText("••••••••") # nie podajemy hashu md5, źle to wygląda
            self.comboBox.setCurrentIndex(roledict[self.userinfo[0][4]]-1) # rola
            
        except (Exception, psycopg2.DatabaseError) as err:
            print(f"Błąd połączenia z bazą: {err}")
            return False
        finally:
            if conn is not None:
                conn.close()                        # zamknięcie konektora do bazy
    
    def updateUserFunction(self, newUserData):
        userid = self.comboBox_2.currentIndex()
        try:
            params = config()                       # wczytujemy paramtery połaczenia z bazą
            conn = psycopg2.connect(**params)       # łączenie z bazą
            cur = conn.cursor()                     # tworzenie kursora do bazy
            query = f"UPDATE uzytkownicy SET imie = '{newUserData['imie']}', nazwisko = '{newUserData['nazwisko']}', email = '{newUserData['email']}', haslo = '{newUserData['haslo']}', rola = '{newUserData['rola']}' WHERE id_uzytkownika = {userid+1}" # query
            cur.execute(query)
            conn.commit()
            self.comboBox_2.setItemText(userid, f"{newUserData['imie']} {newUserData['nazwisko']}") # zmiana nazwy w comboboxie
            messageBox("Sukces", QtWidgets.QMessageBox.Information, "Zmiany zostały zapisane.")
        except (Exception, psycopg2.DatabaseError) as err:
            print(f"Błąd połączenia z bazą: {err}")
            return False
        finally:
            if conn is not None:
                conn.close()                        # zamknięcie konektora do bazy
    
    def validate(self):
        newUserData = {}
        email_regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'

        newUserData["imie"] = self.lineEdit.text()
        newUserData["nazwisko"] = self.lineEdit_2.text()
        newUserData["email"] = self.lineEdit_3.text()
        newUserData["haslo"] = self.lineEdit_4.text()
        newUserData["rola"] = self.comboBox.currentText()
  
        if(self.lineEdit_4.text() == "••••••••"):
            newUserData["haslo"] = self.userinfo[0][3] # nie było zmian w haśle
        else:
            newUserData["haslo"] = hashlib.md5(self.lineEdit_4.text().encode('utf-8')).hexdigest()
        
        if tuple(newUserData.values()) == self.userinfo[0]:
            messageBox("Bez zmian", QtWidgets.QMessageBox.Information, "Nie wprowadzono żadnych zmian.")
            return False
        if '' in newUserData.values():
            messageBox("Błąd", QtWidgets.QMessageBox.Critical, "Wypełnij wszystkie pola")
            return False
        elif not re.fullmatch(email_regex, newUserData["email"]):
            messageBox("Błąd", QtWidgets.QMessageBox.Critical, "Niepoprawny adres email. Adres musi zawierać znak @ i .")
            return False
        else:
            #print(newUserData)
            self.updateUserFunction(newUserData)



    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(472, 465)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 451, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        # Mój kod
        self.comboBox_2.currentIndexChanged.connect(self.getUserInfo)
        self.pushButton.clicked.connect(self.validate)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Zmiana właściwości użytkownika"))
        self.label.setText(_translate("Dialog", "Zmiana właściwości użytkownika"))
        self.label_5.setText(_translate("Dialog", "Użytkownik"))
        self.label_6.setText(_translate("Dialog", "Imię"))
        self.label_7.setText(_translate("Dialog", "Nazwisko"))
        self.label_2.setText(_translate("Dialog", "E-mail"))
        self.label_3.setText(_translate("Dialog", "Hasło"))
        self.label_4.setText(_translate("Dialog", "Rola"))
        self.comboBox.setItemText(0, _translate("Dialog", "Uczeń"))
        self.comboBox.setItemText(1, _translate("Dialog", "Nauczyciel"))
        self.comboBox.setItemText(2, _translate("Dialog", "Admin"))
        self.pushButton.setText(_translate("Dialog", "Zmień użytkownika"))
