# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\updatenote.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# todo: naprawić błąd, nic się nie wyświetla przy klikaniu zatwierdź

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UpdateNote(object):

    def __init__(self, main):
        self.main = main
        self.grades = ['1', '1+', '2-', '2', '2+', '3-', '3', '3+', '4-', '4', '4+', '5-', '5', '5+', '6-', '6', '6+']
        Dialog = QtWidgets.QDialog()
        self.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()

    def fillData(self):
        rows = self.main.db.fetchall(f"SELECT skrot_sprawdzianu FROM sprawdziany WHERE id_przedmiotu = {self.main.class_id} ORDER BY id_sprawdzianu")
        for row in rows:
            self.comboBox.addItem(row[0])
        rows = self.main.db.fetchall(f"SELECT CONCAT_WS(' ', imie, nazwisko) FROM uzytkownicy JOIN uzytkownicy_przedmioty ON uzytkownicy.id_uzytkownika = uzytkownicy_przedmioty.id_uzytkownika WHERE id_przedmiotu = {self.main.class_id} ORDER BY uzytkownicy.id_uzytkownika")
        for row in rows:
            self.comboBox_2.addItem(row[0])
        self.getCurrentGrade() # dla pierwszego elementu
    
    def getCurrentGrade(self):
            row = self.main.db.fetchone(f"SELECT ocena FROM oceny JOIN sprawdziany ON oceny.id_sprawdzianu = sprawdziany.id_sprawdzianu JOIN przedmioty ON sprawdziany.id_przedmiotu = przedmioty.id_przedmiotu JOIN uzytkownicy ON oceny.id_ucznia = uzytkownicy.id_uzytkownika WHERE skrot_sprawdzianu = '{self.comboBox.currentText()}' AND CONCAT_WS(' ', imie, nazwisko) = '{self.comboBox_2.currentText()}'")
            if row is not None: # dany uczeń nie ma oceny
                self.comboBox_3.setCurrentIndex(self.grades.index(row[0]))

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 367)
        Dialog.setAcceptDrops(False)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 290, 401, 17))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 62, 441, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 330, 441, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        # Mój kod
        self.label_7.setText(f"Przedmiot: {self.main.class_shortcut}")
        self.fillData()
        self.comboBox.currentTextChanged.connect(self.getCurrentGrade)
        self.comboBox_2.currentTextChanged.connect(self.getCurrentGrade)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dodawanie oceny"))
        self.label.setText(_translate("Dialog", "Zmiana oceny"))
        self.label_2.setText(_translate("Dialog", "Sprawdzian"))
        self.label_3.setText(_translate("Dialog", "Uczeń"))
        self.label_4.setText(_translate("Dialog", "Ocena"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "1+"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "2-"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "2"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "2+"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "3-"))
        self.comboBox_3.setItemText(6, _translate("Dialog", "3"))
        self.comboBox_3.setItemText(7, _translate("Dialog", "3+"))
        self.comboBox_3.setItemText(8, _translate("Dialog", "4-"))
        self.comboBox_3.setItemText(9, _translate("Dialog", "4"))
        self.comboBox_3.setItemText(10, _translate("Dialog", "4+"))
        self.comboBox_3.setItemText(11, _translate("Dialog", "5-"))
        self.comboBox_3.setItemText(12, _translate("Dialog", "5"))
        self.comboBox_3.setItemText(13, _translate("Dialog", "5+"))
        self.comboBox_3.setItemText(14, _translate("Dialog", "6-"))
        self.comboBox_3.setItemText(15, _translate("Dialog", "6"))
        self.label_6.setText(_translate("Dialog", "Wartość oceny"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Zwykła"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "Semestralna"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "Końcowa"))
        self.pushButton.setText(_translate("Dialog", "Dodaj ocenę"))


